# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master
- release

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.Wpf.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetCoreVersion: '3.0.x'

steps:
- task: UseDotNet@2
  displayName: 'Use dotNet $(dotNetCoreVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotNetCoreVersion)'

- task: NuGetToolInstaller@0
  displayName: 'Use latest NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: |
     $(solution)

- powershell: .paket\paket.exe restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU" /p:MDIX_CORE_VERSION=$(mdixVersion).$(Build.BuildID) /p:MDIX_COLORS_VERSION=$(mdixColorsVersion).$(Build.BuildID) /p:MDIX_MAHAPPS_VERSION=$(mdixMahappsVersion).$(Build.BuildID)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(solution)'

- task: PublishPipelineArtifact@0
  name: "PublishDemoApp"
  inputs:
    artifactName: 'DemoApp'
    targetPath: 'MainDemo.Wpf/bin/$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Copy MDIX nuspec'
  inputs:
    targetType: 'inline'
    script: 'Copy-Item -Path ".\\MaterialDesignThemes.nuspec" -Destination ".\\MaterialDesignThemes.Wpf\\bin\\$(buildConfiguration)\\"'
    ignoreLASTEXITCODE: true

- task: PowerShell@2
  displayName: 'Copy MDIX Colors nuspec'
  inputs:
    targetType: 'inline'
    script: 'Copy-Item -Path ".\\MaterialDesignColors.nuspec" -Destination ".\\MaterialDesignColors.Wpf\\bin\\$(buildConfiguration)\\"'
    ignoreLASTEXITCODE: true

- task: PowerShell@2
  displayName: 'Copy MDIX MahApps nuspec'
  inputs:
    targetType: 'inline'
    script: 'Copy-Item -Path ".\\MaterialDesignThemes.MahApps.nuspec" -Destination ".\\MaterialDesignThemes.MahApps\\bin\\$(buildConfiguration)\\"'
    ignoreLASTEXITCODE: true

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesign"
  inputs:
    artifactName: 'MDIX'
    targetPath: 'MaterialDesignThemes.Wpf/bin/$(buildConfiguration)'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignColors"
  inputs:
    artifactName: 'MDIX.Colors'
    targetPath: 'MaterialDesignColors.Wpf/bin/$(buildConfiguration)'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignMahApps"
  inputs:
    artifactName: 'MDIX.MahApps'
    targetPath: 'MaterialDesignThemes.MahApps/bin/$(buildConfiguration)'